version: '3.0'

networks:
  secNetwork:

services:
  rendering:
    image: 'seccurate:render'
    networks:
      secNetwork:
  crawler:
    image: 'seccurate:crawler'
    networks:
      secNetwork:
  api_gateway:
    image: 'seccurate:apiGateway'
    ports:
      - '3001:3001'
    depends_on:
      - mySQL
    networks:
      secNetwork:
  mySQL:
    image: 'seccurate:mySQL'
    environment:
        MYSQL_ROOT_PASSWORD: 311248496
    networks:
      secNetwork:
  vulnerabilities:
    image: 'seccurate:vulnerabilities'
    networks:
      secNetwork:
  client:
    image: 'seccurate:client'
    networks:
      secNetwork:
  ports:
    - '3000:30000'