version: '3.0'

networks:
  secNetwork:

services:
  rendering:
    image: 'seccurate:render'
    networks:
      secNetwork:
  crawler:
    image: 'seccurate:crawler'
    networks:
      secNetwork:
  api_gateway:
    image: 'seccurate:apiGateway'
    ports:
      - '3001:3001'
    depends_on:
      - mySQL
    networks:
      secNetwork:
  mySQL:
    image: 'seccurate:mySQL'
    environment:
      ['MYSQL_ROOT_PASSWORD=311248496',MYSQL_PORT=3306]
    networks:
      secNetwork: