version: '3.0'

networks:
  secNetwork:

services:
  rendering:
    image: 'seccurate:render'
    networks:
      secNetwork:
  crawler:
    image: 'seccurate:crawler'
    networks:
      secNetwork:
  api_gateway:
    image: 'seccurate:apiGateway'
    ports:
      - '3001:3001'
    depends_on:
      - mySQL
    networks:
      secNetwork:
  mySQL:
    image: 'seccurate:mySQL'
    environment:
        MYSQL_ROOT_PASSWORD: 311248496
    networks:
      secNetwork:
  vulnerabilities:
    image: 'seccurate:vulnerabilities'
    networks:
      secNetwork:
    environment:
      PYTHONPATH: /opt/Seccurate/:/opt/Seccurate/vulnerabilities/:/opt/Seccurate/vulnerabilities/Scanner/common//opt/Seccurate/vulnerabilities/Scanner/dao/:/opt/Seccurate/vulnerabilities/Scanner/data/:/opt/Seccurate/vulnerabilities/Scanner/layout/:/opt/Seccurate/vulnerabilities/Scanner/logic//opt/Seccurate/vulnerabilities/Scanner/Test/:/opt/Seccurate/vulnerabilities/Scanner/:/opt/Seccurate/vulnerabilities/Scanner/layout/boundaries/:/opt/Seccurate/vulnerabilities/Scanner/common/exceptions/:/opt/Seccurate/vulnerabilities/Scanner/common/QueueMessages/
  client:
    image: 'seccurate:client'
    networks:
      secNetwork:
  ports:
    - '3000:30000'